CREATE TABLE IF NOT EXISTS Usuario (
    cpf BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    senha_hash VARCHAR(255) NOT NULL,
    email_login VARCHAR(255) NOT NULL UNIQUE,
    nome VARCHAR(255) NOT NULL,
    CONSTRAINT chk_senha_tamanho CHECK (CHAR_LENGTH(senha_hash) >=8),
    num_tel BIGINT NOT NULL,
    data_nasc DATE NOT NULL,
    data_criacao TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB
  DEFAULT CHARSET=utf8mb4
  COLLATE=utf8mb4_general_ci;

CREATE TABLE IF NOT EXISTS Tipo (
    id_tipo INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    nome_tipo VARCHAR (255) NOT NULL UNIQUE
) ENGINE=InnoDB
  DEFAULT CHARSET=utf8mb4
  COLLATE=utf8mb4_general_ci;

CREATE TABLE IF NOT EXISTS Log_BD(
    id_log INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    data_evento TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    nivel VARCHAR (20) NOT NULL,
    mensagem VARCHAR(255) NOT NULL,
    contexto TEXT
) ENGINE=InnoDB
  DEFAULT CHARSET=utf8mb4
  COLLATE=utf8mb4_general_ci;

CREATE TABLE IF NOT EXISTS Produto (
    id_produto INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    valor DECIMAL(10,2) NOT NULL,
    nome VARCHAR(255) NOT NULL,
    imagem VARCHAR(255) NOT NULL,
    data_criacao TIMESTAMP DEFAULT CURRENT TIMESTAMP,
    id_tipo INT UNSIGNED,
   FOREIGN KEY (id_tipo) REFERENCES Tipos(id_tipo)
) ENGINE=InnoDB
  DEFAULT CHARSET=utf8mb4
  COLLATE=utf8mb4_general_ci;

CREATE INDEX idx_produto_tipo ON Produto(id_tipo);
CREATE INDEX idx_log_nivel ON Log_BD(nivel);